"""
SP500 universe: ~150 representative stocks mapped to GICS sectors.
Expand STOCKS list to add more symbols — sector mapping is the only requirement.
"""

# GICS sector names
SECTORS = [
    "Information Technology",
    "Health Care",
    "Financials",
    "Consumer Discretionary",
    "Communication Services",
    "Industrials",
    "Consumer Staples",
    "Energy",
    "Utilities",
    "Real Estate",
    "Materials",
]

# symbol → sector
STOCK_SECTOR: dict[str, str] = {
    # Information Technology
    "AAPL": "Information Technology",
    "MSFT": "Information Technology",
    "NVDA": "Information Technology",
    "AVGO": "Information Technology",
    "ORCL": "Information Technology",
    "CRM": "Information Technology",
    "ADBE": "Information Technology",
    "AMD": "Information Technology",
    "QCOM": "Information Technology",
    "TXN": "Information Technology",
    "AMAT": "Information Technology",
    "MU": "Information Technology",
    "LRCX": "Information Technology",
    "KLAC": "Information Technology",
    "INTC": "Information Technology",
    "IBM": "Information Technology",
    "NOW": "Information Technology",
    "SNOW": "Information Technology",
    "PANW": "Information Technology",
    # Health Care
    "UNH": "Health Care",
    "LLY": "Health Care",
    "JNJ": "Health Care",
    "ABBV": "Health Care",
    "MRK": "Health Care",
    "TMO": "Health Care",
    "ABT": "Health Care",
    "DHR": "Health Care",
    "ISRG": "Health Care",
    "SYK": "Health Care",
    "VRTX": "Health Care",
    "REGN": "Health Care",
    "BMY": "Health Care",
    "AMGN": "Health Care",
    "MDT": "Health Care",
    "PFE": "Health Care",
    "GILD": "Health Care",
    "CVS": "Health Care",
    "CI": "Health Care",
    # Financials
    "BRK.B": "Financials",
    "JPM": "Financials",
    "V": "Financials",
    "MA": "Financials",
    "BAC": "Financials",
    "WFC": "Financials",
    "GS": "Financials",
    "MS": "Financials",
    "BLK": "Financials",
    "AXP": "Financials",
    "SPGI": "Financials",
    "C": "Financials",
    "CB": "Financials",
    "PGR": "Financials",
    "USB": "Financials",
    "TFC": "Financials",
    "SCHW": "Financials",
    # Consumer Discretionary
    "AMZN": "Consumer Discretionary",
    "TSLA": "Consumer Discretionary",
    "HD": "Consumer Discretionary",
    "MCD": "Consumer Discretionary",
    "NKE": "Consumer Discretionary",
    "LOW": "Consumer Discretionary",
    "SBUX": "Consumer Discretionary",
    "TJX": "Consumer Discretionary",
    "BKNG": "Consumer Discretionary",
    "ABNB": "Consumer Discretionary",
    "GM": "Consumer Discretionary",
    "F": "Consumer Discretionary",
    "EBAY": "Consumer Discretionary",
    "RCL": "Consumer Discretionary",
    "CCL": "Consumer Discretionary",
    # Communication Services
    "GOOGL": "Communication Services",
    "META": "Communication Services",
    "NFLX": "Communication Services",
    "DIS": "Communication Services",
    "CMCSA": "Communication Services",
    "T": "Communication Services",
    "VZ": "Communication Services",
    "TMUS": "Communication Services",
    "EA": "Communication Services",
    "TTWO": "Communication Services",
    "WBD": "Communication Services",
    "FOXA": "Communication Services",
    # Industrials
    "GE": "Industrials",
    "HON": "Industrials",
    "CAT": "Industrials",
    "UPS": "Industrials",
    "RTX": "Industrials",
    "DE": "Industrials",
    "LMT": "Industrials",
    "BA": "Industrials",
    "MMM": "Industrials",
    "GD": "Industrials",
    "FDX": "Industrials",
    "NSC": "Industrials",
    "UNP": "Industrials",
    "EMR": "Industrials",
    "ETN": "Industrials",
    # Consumer Staples
    "WMT": "Consumer Staples",
    "PG": "Consumer Staples",
    "KO": "Consumer Staples",
    "PEP": "Consumer Staples",
    "COST": "Consumer Staples",
    "PM": "Consumer Staples",
    "MO": "Consumer Staples",
    "CL": "Consumer Staples",
    "KMB": "Consumer Staples",
    "GIS": "Consumer Staples",
    "K": "Consumer Staples",
    "SYY": "Consumer Staples",
    # Energy
    "XOM": "Energy",
    "CVX": "Energy",
    "COP": "Energy",
    "SLB": "Energy",
    "EOG": "Energy",
    "MPC": "Energy",
    "PSX": "Energy",
    "VLO": "Energy",
    "OXY": "Energy",
    "HAL": "Energy",
    "DVN": "Energy",
    # Utilities
    "NEE": "Utilities",
    "DUK": "Utilities",
    "SO": "Utilities",
    "D": "Utilities",
    "AEP": "Utilities",
    "EXC": "Utilities",
    "SRE": "Utilities",
    "PEG": "Utilities",
    "XEL": "Utilities",
    "WEC": "Utilities",
    # Real Estate
    "PLD": "Real Estate",
    "AMT": "Real Estate",
    "EQIX": "Real Estate",
    "CCI": "Real Estate",
    "PSA": "Real Estate",
    "O": "Real Estate",
    "WELL": "Real Estate",
    "DLR": "Real Estate",
    "AVB": "Real Estate",
    "EQR": "Real Estate",
    # Materials
    "LIN": "Materials",
    "APD": "Materials",
    "SHW": "Materials",
    "FCX": "Materials",
    "NEM": "Materials",
    "ECL": "Materials",
    "DD": "Materials",
    "PPG": "Materials",
    "VMC": "Materials",
    "MLM": "Materials",
}

SYMBOLS: list[str] = list(STOCK_SECTOR.keys())


def get_sector(symbol: str) -> str:
    return STOCK_SECTOR.get(symbol, "Unknown")


def symbols_by_sector() -> dict[str, list[str]]:
    result: dict[str, list[str]] = {s: [] for s in SECTORS}
    for sym, sec in STOCK_SECTOR.items():
        if sec in result:
            result[sec].append(sym)
    return result
